### ISSUE TITLE
doctor-doom usually restart

### ISSUE THREAD

**Issue by mrnim94** [mrnim94/doctor-doom#16]
We have the error:
```Conquer the world, destroy victims 🔥🔥🔥
Run with options:  {/app/downloaded * * * * * /var/log/doctor-doom {1h * 0B} true}
Start conquer the world 🌋
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x53e6e8]

goroutine 34 [running]:
github.com/mrnim94/doctor-doom/common/utils.(*FileUtils).ListAllFilesMatch.func1({0xc000e81270, 0x50}, {0x0, 0x0}, {0xc000095598?, 0xffffffffffffff9c?})
   /go/src/doctor-doom/common/utils/file_utils.go:71 +0x88
path/filepath.walk({0xc00001c00a, 0xf}, {0x78eef8, 0xc0001941a0}, 0xc000095598)
   /usr/local/go/src/path/filepath/path.go:453 +0x209
path/filepath.Walk({0xc00001c00a, 0xf}, 0xc000095598)
   /usr/local/go/src/path/filepath/path.go:520 +0x6c
github.com/mrnim94/doctor-doom/common/utils.(*FileUtils).ListAllFilesMatch(0x0?, {0xc00001c00a?, 0x2?}, 0x0?, 0x0?, {0xc00001e03a?, 0x0?}, 0x0?)
   /go/src/doctor-doom/common/utils/file_utils.go:70 +0x93
github.com/mrnim94/doctor-doom/doom.(*DoctorDoom).GetDoomVictims(0xc00015ea80)
   /go/src/doctor-doom/doom/doom.go:51 +0x86
github.com/mrnim94/doctor-doom/doom.(*DoctorDoom).Destroy(0x0?)
   /go/src/doctor-doom/doom/doom.go:154 +0x1e
reflect.Value.call({0x6ae380?, 0xc0001763e0?, 0x13?}, {0x7070b8, 0x4}, {0x997730, 0x0, 0x0?})
   /usr/local/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0x6ae380?, 0xc0001763e0?, 0xedb912244?}, {0x997730?, 0xc0001845f0?, 0xc000184650?})
   /usr/local/go/src/reflect/value.go:368 +0xbc
github.com/go-co-op/gocron.callJobFuncWithParams({0x6ae380?, 0xc0001763e0?}, {0x0, 0x0, 0xb9dd19?})
   /go/pkg/mod/github.com/go-co-op/gocron@v1.18.0/gocron.go:106 +0x155
github.com/go-co-op/gocron.(*executor).start.func1.2()
   /go/pkg/mod/github.com/go-co-op/gocron@v1.18.0/executor.go:93 +0x66
github.com/go-co-op/gocron.(*executor).start.func1()
   /go/pkg/mod/github.com/go-co-op/gocron@v1.18.0/executor.go:100 +0x4a9
created by github.com/go-co-op/gocron.(*executor).start
   /go/pkg/mod/github.com/go-co-op/gocron@v1.18.0/executor.go:51 +0x71
```

**Comment by mrnim94** [comment]
We will ignore no such file or directory
